
pipeline { 
    agent any 
        stages { 
            stage ('Build') { 
                steps { 
                    echo 
                    'Running build phase. ' 
                }
            }
        }
    }
1
2
3
4
5
6
7
8
9
10
11
pipeline { 
    agent any 
        stages { 
            stage ('Build') { 
                steps { 
                    echo 
                    'Running build phase. ' 
                }
            }
        }
    }
